name: qbittorrent_api
description: Dart wrapper for qBittorrent Web API.
version: 1.0.0
repository: https://github.com/yosemiteyss/qbittorrent_api

environment:
  sdk: ^3.0.0

dependencies:
  cookie_jar: ^4.0.5
  dio: ^5.2.0
  dio_cookie_manager: ^3.1.0
  json_annotation: ^4.8.1
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  fake_async: ^1.3.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
